name: Respond to Issue Comment

on:
  issue_comment:
    types: [created]

jobs:
  respond_to_comment:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Respond to Comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          const { Octokit } = require("@octokit/rest");

          const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

          async function run() {
            const { payload } = JSON.parse(process.env.GITHUB_EVENT_PATH);
            const comment = payload.comment.body;

            if (comment) {
              console.log("hi");
              // Optional: Add code to update or interact with GitHub Project board if desired
            } else {
              console.log("No comment found.");
            }
          }

          run().catch(err => console.error(err));
